### ISSUE TITLE
Thanks for this module

### ISSUE THREAD

**Issue by dotlouis** [goto-bus-stop/mongoose-model-decorators#1]
Hey, Just wanted to drop a line:
Thanks a lot for this module. When I decided to really dive into ES7 decorators a few days ago, I immediately thought they would be a good fit for mongoose models.
And just before opening up my editor to start working on it, I looked it up on google to see if someone already had this idea and found this module. I'll let you know how it works out in my project. I noticed the repo is really new and I'm willing to contribute. :)
Cheers

_(You can close this issue of course)_

**Comment by goto-bus-stop** [comment]
:smile: thanks for the message! I see you've already found an improvement, that's great :+1:
