### ISSUE TITLE
Specify which connection to attach the model to

### ISSUE THREAD

**Issue by dotlouis** [goto-bus-stop/mongoose-model-decorators#2]
Referring to [this](http://stackoverflow.com/questions/10156623/mongoose-js-instance-save-callback-not-firing) issue I stumbled upon.
That would be useful to find a way to tell the model decorator to attach to a given connection object created with `mongoose.createConnection()` instead of `mongoose.connect()`.
For example, to attach different models to different mongo databases.

**Comment by goto-bus-stop** [comment]
Good catch, I think a `connection` option for `@Model` would be a pretty good fix:

``` js
const myConnection = mongoose.createConnection('mongodb://somewhere.com:27017/else')
```

``` js
@Model({ connection: myConnection })
class User {
  // …
}
```

It'd also be nice to be able to set a `connection` static property, for consistency with how Schema options work

``` js
@Model
class User {
  static connection = myConnection;
  // …
}
```

If that sounds good to you, I might add it in the weekend, but definitely feel free to send a PR (or opinion) in the mean time :)

**Comment by dotlouis** [comment]
That's exactly what I meant.
I will try to submit a PR even though I may not be qualified enough.
