### ISSUE TITLE
compound indexes?

### ISSUE THREAD

**Issue by langfors** [goto-bus-stop/mongoose-model-decorators#20]
Is there a way to configure 'compound indexes' on these models?

https://docs.mongodb.com/manual/indexes/#Indexes-CompoundKeys

Mongoose supports this with this syntax: e.g.

    UserSchema.index({"name":1, "source": 1, "medium": 1}, {"unique": true});

Thanks!

**Comment by goto-bus-stop** [comment]
Hi! Not really, the best you can do at the moment is:

```js
@Schema
class UserSchema {
  static schema = { /* etc */ }
}
const userSchema = new UserSchema()
userSchema.index({ name: 1, etc: 1 }, {})

mongoose.model('User', userSchema)
```

which is a bit clumsy

**Comment by goto-bus-stop** [comment]
Added a `configureSchema` hook for this kind of thing in https://github.com/goto-bus-stop/mongoose-model-decorators/commit/c18833a6561d3559861800c3f5a3ec6eacdaeeaf:

```js
@Model
class User {
  static schema = { /* ... */ }
  static configureSchema (schema) {
    schema.index({ name: 1, source: 1, medium: 1 }, { unique: true })
  }
}
```
