### ISSUE TITLE
Allow custom constructors

### ISSUE THREAD

**Issue by dotlouis** [goto-bus-stop/mongoose-model-decorators#3]
Hi,
Maybe this question has a broader scope than this module,
but I was wondering if it's possible to create a custom constructor for a Model.
I saw [in your code](https://github.com/goto-bus-stop/mongoose-model-decorators/blob/master/src/Schema.js#L13) that you were ignoring the constructor method.

Basically I want to be able to do this:

``` js
@Model
class Event{

    static schema = {
        start: { type: Date, required: true },
        end: { type: Date, required: true },
        duration: { type: String, required: true }
    };

    constructor(params = {}){

        // set complex defaults, computed properties, validate params and more
        let start = moment(params.start) || moment();
        let duration = moment.duration(params.duration) || moment.duration(1,'h');
        let end = moment(params.end) || moment(start).add(duration);

        // somehow call the Mongoose model constructor with 'this' as an argument
    }
}
```

I'm aware that Mongoose already have validators, default properties and virtuals properties.
But doing this things through a constructor feels more _natural_  and less dependant on how Mongoose works (through a Schema).
Besides, it lets you work with properties in your model that you don't always want to be persisted in Mongo.
For example here I want to be able to call my Event constructor like so:

``` js
// no params, defaults will apply (start is now, duration is 1h and end computed)
new Event();
// a start and a duration (end is computed)
new Event(new Date(),'3h'); 
// a start and end (duration is computed)
new Event(new Date(),new Date()+10000);
```

I also want my server to be able to work directly with moment objects without having to convert Dates back and forth at saving time.

Here, I think it's a little confusing. Maybe I'm horribly wrong, but it definitely felt like this was the most natural way of creating an Event.
I gladly welcome opinions and advices.
Thanks

Links:
- [Custom constructor function in Mongoose schema/models](http://stackoverflow.com/questions/14217067/custom-constructor-function-in-mongoose-schema-models)
- [Allow for Custom Constructors](https://github.com/Automattic/mongoose/issues/1502)
- [Constructor function in Mongoose schema/models](http://stackoverflow.com/questions/15214836/constructor-function-in-mongoose-schema-models)
- [ilsken/mongoose-construct](https://github.com/ilsken/mongoose-construct)

**Comment by goto-bus-stop** [comment]
The most natural way to do this would probably be using `super`:

``` js
@Model
class Event {
  // ...
  constructor(start, end) {
    validateEtc(start, end)
    super({ start: start, end: end })
  }
}
```

However a `super()` call can only occur in a subclass (`class Event extends Something {}`)… Perhaps a `this.init` or somesuch call could be an okay alternative. It's not quite perfect, but worth considering:

``` js
@Model
class Event {
  // ...
  constructor(start, end) {
    validateEtc(start, end)
    this.init({ start: start, end: end })
  }
}
```

**Comment by dotlouis** [comment]
Interesting but the constructor does not effectively get called, because the class Event is not used as such but rather transformed into a Mongoose Model Class.
Picking up on what you said about inheritance, would it be suitable to use the decorator to create a subclass of a Mongoose model to allow the use of custom constructor and `super()` ?
I'm not sure yet, I'm just offering food for thoughts.
Right now I'm going to use [mongoose-construct](https://github.com/ilsken/mongoose-construct) for my validating and defaulting needs. I'll try to report what are my opinions on the subject here.

**Comment by dotlouis** [comment]
I want to share my findings about this subject.
So [mongoose-construct](https://github.com/ilsken/mongoose-construct) seemed a good idea, but I couldn't make it work with the lastest version of mongoose (4.x).
I finally chose the static constructor way as [this stackoverflow answer](http://stackoverflow.com/questions/14217067/custom-constructor-function-in-mongoose-schema-models/25454730#25454730) suggest.
However I really wanted to create an object with the `new` operand.
So I extended my Model like so:

``` js
@Model
class Event{

  static schema = {
    start: { type: Date, required: true },
    end: { type: Date, required: true },
    duration: { type: String, required: true }
  };

  static spawn(params = {}){
    // do things with parameters, such as setting defaults based on other params. (can't do that with Mongoose defaults)
    // you could do this in a pre('save') hook but you wouldn't be able to instantiate the object with correct defaults without saving it.

    // return the instance you want with parameters correctly set as defined in the schema
    return (new this(correctParams));
  }

  /*
  * ... rest of the class
  */

}


export default class extends Event{
  constructor(
    super();
    return Event.spawn(params);
  }
}
```

Now you can do something like

``` js
import Event from './event.model'

let e = new Event(); // calls Event.spawn() under the hood
e.save(); // save it when you want
```

I'm pretty happy with this, although I'm sure I can still improve it by making some sort of `@construct`decorator for the spawn method to abstract the class inheritance.
